#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

mj12_ - Wildcard-plugin to monitor majestic12 nodes.

=head1 CONFIGURATION

This plugin does not normally require configuration but it needs
xur17's MJ12monitor.jhh, which you can find here:
https://github.com/xur17/MJ12Monitor/blob/master/MJ12Monitor.jhh
A copy of this file is located here:
http://dontrm.org/8212858d1d99b57cdc5f9fb3cc9474c7
You must put these files into the /htdocs/tools/ directory of your
majestic12 node to work properly.

If your server does not listens to 127.0.0.1 port 1088 or your
username and password are not default you must specify some
configuration values as showed in this example:

  [mj12_1]
    env.
    env.host 127.0.0.1
    env.port 1088
    env.user majesticuser
    env.pass secret
    env.ignore_<parameter> true

The last line of the above example completely hides a statistic line
from the entire graph. It may take a bit, until the result is visible.

This is a wildcard plugin. To monitor an majestic12 node, link mj12_
to this file. E.g.

  ln -s /usr/share/munin/plugins/mj12_ /etc/munin/plugins/mj12_1

...will monitor the first specified server.

=head1 AUTHOR

  fusl (Kevin Holly (Dedilink.eu))

=head1 LICENSE

GNU General Public License

=head1 VERSION

  $Id: mj12_.in 2 2012-09-14 20:42:46Z fusl $

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

NODEID=${0##*/mj12_}
HOST="${host:-127.0.0.1}"
PORT="${port:-1088}"
[ "$user" ] && USERNAME="--http-user=$user"
[ "$pass" ] && PASSWORD="--http-password=$pass"
relativelist="totalurls successes notfound timedout disallowed banned dnserrors connerrors forbidden403 other retries downloadeddata overalldownload uploadeddata overallupload"
absolutelist="currentdownload downloadlimit currentupload uploadlimit"

case $1 in
	config)
		echo "graph_title Majestic12 Stats for $HOST:$PORT (ID $NODEID)"
		echo "graph_vlabel average x per second"
		echo "graph_category network"
		echo "graph_info This graph shows Majestic12 node statistics for $HOST:$PORT (ID $NODEID)"
		for relatives in $relativelist
		do
			hideignored="ignore_$relatives"
			if [ ! "${!hideignored}" ]
			then
				echo "$relatives.label $relatives"
				echo "$relatives.type COUNTER"
			fi
		done
		for absolutes in $absolutelist
		do
			hideignored="ignore_$absolutes"
			if [ ! "${!hideignored}" ]
			then
				echo "$absolutes.label $absolutes"
				echo "$absolutes.type GAUGE"
			fi
		done
	;;
	*)
		wget -q -O- $USERNAME $PASSWORD http://$HOST:$PORT/tools/MJ12Monitor.jhh | while read line
		do
			column="`echo $line | tr -d ' ()' | awk -F':' '{print tolower($1)}'`"
			hideignored="ignore_$column"
			value="`echo $line | tr -d ' ,' | awk -F':' '{print $2}' | awk -F'(' '{print $1}'`"
			for key in $relativelist $absolutelist
			do
				[ "$key" == "$column" ] && ([ ! "${!hideignored}" ] && echo "$key.value $value") && continue
			done
		done
	;;
esac
